name: Publish new version

on:
  workflow_dispatch:
    
  schedule:
    - cron: "0 7 * * *"

  repository_dispatch:
    types:
      - webhook

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - run: |
        date +%s > lastUpdate
        git config user.name FabianHermar
        git config user.email contactofabianmartinez@gmail.com
        git add lastUpdate
        git diff --quiet && git diff --staged --quiet || git commit -m "[bot] Update README with latest info"
        git push origin master